version: "2.1"
services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=thisforyou.duckdns.org
      - TOKEN=token
      - LOG_FILE=false
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8050:80
    restart: unless-stopped
